'use client';
import {useEffect,useMemo,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Row={prospect_id:string;campaign_id:string;client:string;campaign:string;prospect:string;stage:number;reply_status:string;confidence:number;due_date:string;next:string;status:string};
type ReadyEmail={id:string;prospect_id:string;number:number;subject:string;body:string;cta:string;prospect:string;row:Row};
const FILTERS=['all','needs attention','ready','waiting','replied','meeting','closed','error','low confidence'];

export default function Home(){
 const [rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState('all'),[email,setEmail]=useState<ReadyEmail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{try{const response=await fetch(`${API}/api/dashboard`);if(!response.ok)throw new Error('Dashboard could not load');setRows(await response.json());setError('')}catch(e:any){setError(e.message||'API unavailable')}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setEmail(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 const visible=useMemo(()=>rows.filter(r=>filter==='all'||(filter==='low confidence'?r.confidence<.75:filter==='needs attention'?['new','researched','ready','error'].includes(r.status):r.status===filter)),[rows,filter]);
 const generate=async(row:Row)=>{setBusy('generate');setError('');try{const response=await fetch(`${API}/api/prospects/${row.prospect_id}/generate-next`,{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Email could not be generated');setEmail({...data,prospect:row.prospect,row})}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const move=async(direction:number)=>{if(!email||visible.length<2)return;const current=visible.findIndex(r=>r.prospect_id===email.prospect_id);const next=(current+direction+visible.length)%visible.length;await generate(visible[next])};
 const save=async()=>{if(!email)return null;const response=await fetch(`${API}/api/emails/${email.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:email.subject,body:email.body,cta:email.cta})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Email changes could not be saved');return data};
 const tryAgain=async()=>{if(!email)return;setBusy('regenerate');setError('');try{const response=await fetch(`${API}/api/emails/${email.id}/regenerate`,{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Email could not be regenerated');setEmail({...email,...data})}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const markSentAndNext=async()=>{if(!email)return;setBusy('sent');setError('');const currentIndex=visible.findIndex(r=>r.prospect_id===email.prospect_id);const nextRow=visible.length>1?visible[(currentIndex+1)%visible.length]:null;try{await save();const response=await fetch(`${API}/api/emails/${email.id}/sent`,{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Email could not be marked sent');await load();if(nextRow)await generate(nextRow);else setEmail(null)}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const exportAll=()=>window.open(`${API}/api/batch/export-all?generate=false`,'_blank');
 return <main>
  <aside><div className="brand">NARRATIVE<span>OS</span></div><nav>{FILTERS.map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</nav><div className="autonomy"><b>Autonomy on</b><small>Seller approval is the only checkpoint</small></div></aside>
  <section><header><div><p className="eyebrow">OUTBOUND COMMAND CENTER</p><h1>What happens next</h1></div><div className="headerActions"><button className="secondary" onClick={exportAll}>Download ready CSV</button><button className="primary" onClick={()=>void load()}>Refresh</button></div></header>
  {error&&<div className="error">{error}</div>}
  <div className="stats"><article><b>{rows.filter(r=>['new','researched','ready'].includes(r.status)).length}</b><span>Need attention</span></article><article><b>{rows.filter(r=>r.status==='waiting').length}</b><span>Waiting</span></article><article><b>{rows.filter(r=>r.status==='meeting').length}</b><span>Meetings</span></article><article><b>{rows.filter(r=>r.confidence<.75).length}</b><span>Low confidence</span></article></div>
  <div className="table"><div className="tr head"><span>Prospect</span><span>Campaign</span><span>Stage</span><span>Confidence</span><span>Status</span><span>NEXT</span></div>{visible.map(r=><div className={`tr selectable ${email?.prospect_id===r.prospect_id?'selected':''}`} key={r.prospect_id} onClick={()=>void generate(r)}><span><b>{r.prospect}</b><small>{r.client}</small></span><span>{r.campaign}</span><span>{r.stage}/5</span><span><i className={r.confidence<.75?'low':''}>{Math.round(r.confidence*100)}%</i></span><span className="status">{r.status}</span><span><button className="next" disabled={busy==='generate'}>{busy==='generate'&&email?.prospect_id===r.prospect_id?'Working…':`${r.next} →`}</button></span></div>)}</div>
  {!visible.length&&<div className="empty">No prospects match this view.</div>}</section>
  {email&&<div className="drawer"><div className="previewClose"><button onClick={()=>setEmail(null)}>← Close preview</button><small>Esc</small></div><div className="drawerNav"><button onClick={()=>void move(-1)} disabled={visible.length<2}>← Previous</button><span>{Math.max(1,visible.findIndex(r=>r.prospect_id===email.prospect_id)+1)} of {visible.length}</span><button onClick={()=>void move(1)} disabled={visible.length<2}>Next →</button></div><p className="eyebrow">EMAIL {email.number} · READY</p><h2>{email.prospect}</h2><label>SUBJECT</label><div className="copy"><input value={email.subject} onChange={e=>setEmail({...email,subject:e.target.value})}/><button onClick={()=>navigator.clipboard.writeText(email.subject)}>Copy</button></div><label>BODY</label><textarea rows={13} value={email.body} onChange={e=>setEmail({...email,body:e.target.value})}/><label>CTA</label><select value={email.cta} onChange={e=>setEmail({...email,cta:e.target.value})}><option>{email.cta}</option><option>Open to comparing notes?</option><option>Worth a brief conversation?</option><option>Should I send a short example?</option></select><div className="drawerActions"><button className="secondary" disabled={busy==='regenerate'} onClick={()=>void tryAgain()}>{busy==='regenerate'?'Writing…':'Try again'}</button><button className="secondary" onClick={()=>navigator.clipboard.writeText(`${email.subject}\n\n${email.body}`)}>Copy email</button><button className="secondary" onClick={()=>window.open(`${API}/api/batch/export/${email.row.campaign_id}?generate=false`,'_blank')}>Export CSV</button></div><button className="primary wide" disabled={busy==='sent'} onClick={()=>void markSentAndNext()}>{busy==='sent'?'Saving…':'Mark sent & open next'}</button></div>}
 </main>
}