'use client';
import {useEffect,useState} from 'react';
import s from './setup.module.css';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Client={id:string;name:string;main_url:string;extra_urls:string[];profile:any;status:string};
type Campaign={id:string;client_id:string;name:string;target_audience:string;active:boolean};
type Prospect={id:string;campaign_id:string;company_url:string;company_name:string;contact_name:string;contact_title:string;contact_email:string;status:string;stage:number;confidence:number;next_action:string;strategic_brief:any;blueprint:any[]};
type Evidence={id:string;source:string;fact:string;evidence_type:string;confidence:number;kind:string;observed_at:string};
const jsonHeaders={'Content-Type':'application/json'};
async function request(path:string,init?:RequestInit){const r=await fetch(API+path,init);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||`Request failed (${r.status})`);return body}
export default function Setup(){
 const [tab,setTab]=useState('clients'),[clients,setClients]=useState<Client[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[prospects,setProspects]=useState<Prospect[]>([]),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [selectedClient,setSelectedClient]=useState(''),[profileText,setProfileText]=useState(''),[files,setFiles]=useState<FileList|null>(null);
 const [selectedProspect,setSelectedProspect]=useState(''),[evidence,setEvidence]=useState<Evidence[]>([]),[email,setEmail]=useState<any>(null),[csv,setCsv]=useState<File|null>(null);
 const [clientForm,setClientForm]=useState({name:'',main_url:'',extra_urls:''});
 const [campaignForm,setCampaignForm]=useState({client_id:'',name:'',target_audience:'',personas:'Founder, CTO',narrative_strategy:'auto'});
 const [prospectForm,setProspectForm]=useState({campaign_id:'',company_url:'',company_name:'',contact_name:'',contact_title:'',contact_email:'',linkedin_url:'',extra_urls:'',notes:''});
 const flash=(text:string)=>{setMessage(text);setError('')}; const fail=(e:any)=>{setError(e.message||String(e));setMessage('')};
 const load=async()=>{try{const [c,ca,p]=await Promise.all([request('/api/clients'),request('/api/campaigns'),request('/api/prospects')]);setClients(c);setCampaigns(ca);setProspects(p);if(!selectedClient&&c[0])selectClient(c[0]);}catch(e){fail(e)}};
 useEffect(()=>{void load()},[]);
 const selectClient=(c:Client)=>{setSelectedClient(c.id);setProfileText(JSON.stringify(c.profile||{},null,2));setCampaignForm(x=>({...x,client_id:c.id}))};
 async function createClient(e:React.FormEvent){e.preventDefault();setBusy('client');try{const c=await request('/api/clients',{method:'POST',headers:jsonHeaders,body:JSON.stringify({name:clientForm.name,main_url:clientForm.main_url,extra_urls:clientForm.extra_urls.split(/[,\n]/).map(x=>x.trim()).filter(Boolean)})});selectClient(c);flash('Client created. Add source material, then generate the Seller Intelligence Profile.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function uploadSources(){if(!selectedClient||!files?.length)return;setBusy('upload');try{const data=new FormData();Array.from(files).forEach(f=>data.append('files',f));await request(`/api/clients/${selectedClient}/sources`,{method:'POST',body:data});flash(`${files.length} source file(s) stored and ready for profile generation.`)}catch(e){fail(e)}finally{setBusy('')}}
 async function generateProfile(){setBusy('profile');try{const c=await request(`/api/clients/${selectedClient}/generate-profile`,{method:'POST'});setProfileText(JSON.stringify(c.profile,null,2));flash('AI profile generated. This is the one required review step—edit anything necessary, then approve.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function approveProfile(){setBusy('approve');try{const profile=JSON.parse(profileText);await request(`/api/clients/${selectedClient}/approve`,{method:'PUT',headers:jsonHeaders,body:JSON.stringify({profile})});flash('Seller profile approved. Normal campaign operation is now autonomous.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function deleteDraft(){if(!activeClient||activeClient.status!=='draft'||!window.confirm(`Delete draft client ${activeClient.name}?`))return;setBusy('delete');try{await request(`/api/clients/${activeClient.id}`,{method:'DELETE'});setSelectedClient('');setProfileText('');flash('Draft client deleted. Approved clients were not affected.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function createCampaign(e:React.FormEvent){e.preventDefault();setBusy('campaign');try{await request('/api/campaigns',{method:'POST',headers:jsonHeaders,body:JSON.stringify({...campaignForm,personas:campaignForm.personas.split(',').map(x=>x.trim()).filter(Boolean)})});flash('Campaign created.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function createProspect(e:React.FormEvent){e.preventDefault();setBusy('prospect');try{const p=await request('/api/prospects',{method:'POST',headers:jsonHeaders,body:JSON.stringify({...prospectForm,extra_urls:prospectForm.extra_urls.split(/[,\n]/).map(x=>x.trim()).filter(Boolean)})});setSelectedProspect(p.id);flash('Prospect added. Research can now run autonomously.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function researchProspect(id:string){setBusy('research');try{const p=await request(`/api/prospects/${id}/research`,{method:'POST'});setSelectedProspect(id);const ledger=await request(`/api/prospects/${id}/evidence`);setEvidence(ledger);flash(`Research complete in ${p.strategic_brief.mode} mode at ${Math.round(p.confidence*100)}% confidence.`);await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function viewEvidence(id:string){setSelectedProspect(id);setEvidence(await request(`/api/prospects/${id}/evidence`));setTab('evidence')}
 async function generateEmail(id:string){setBusy('email');try{setEmail(await request(`/api/prospects/${id}/generate-next`,{method:'POST'}));setSelectedProspect(id);setTab('evidence');flash('The next required email is ready. No later-stage emails were generated.');await load()}catch(e){fail(e)}finally{setBusy('')}}
 async function importCsv(){if(!csv||!campaignForm.client_id)return;const campaignId=prospectForm.campaign_id||campaigns.find(x=>x.client_id===campaignForm.client_id)?.id;if(!campaignId){fail(new Error('Select a campaign first.'));return}setBusy('csv');try{const data=new FormData();data.append('file',csv);const result=await request(`/api/batch/import/${campaignId}`,{method:'POST',body:data});flash(`${result.created} prospects imported; ${result.errors.length} row errors.`);await load()}catch(e){fail(e)}finally{setBusy('')}}
 const activeClient=clients.find(x=>x.id===selectedClient),activeProspect=prospects.find(x=>x.id===selectedProspect);
 return <div className={s.page}><p className={s.eyebrow}>GUIDED OPERATIONS</p><h1>Build the next conversation</h1><p className={s.lede}>Set up the seller once. From there, research, narrative continuity, CTA selection, and sequence decisions run autonomously.</p>
 <div className={s.steps}>{[['clients','1 · Seller'],['campaigns','2 · Campaign'],['prospects','3 · Prospects'],['evidence','4 · Research & email'],['batch','Batch CSV']].map(([k,v])=><button key={k} className={tab===k?s.active:''} onClick={()=>setTab(k)}>{v}</button>)}</div>
 {message&&<div className={s.notice}>{message}</div>}{error&&<div className={s.error}>{error}</div>}
 {tab==='clients'&&activeClient?.status==='draft'&&<div className={s.actions}><button className={s.danger} disabled={busy==='delete'} onClick={deleteDraft}>Delete selected draft client</button></div>}
 {tab==='clients'&&<div className={s.grid}><form className={s.card} onSubmit={createClient}><h2>Create a client</h2><p>The company doing the selling. URLs and files are processed once and cached.</p><div className={s.field}><label>CLIENT NAME</label><input required value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/></div><div className={s.field}><label>MAIN WEBSITE URL</label><input required type="url" placeholder="https://…" value={clientForm.main_url} onChange={e=>setClientForm({...clientForm,main_url:e.target.value})}/></div><div className={s.field}><label>ADDITIONAL URLS</label><textarea rows={3} placeholder="One per line" value={clientForm.extra_urls} onChange={e=>setClientForm({...clientForm,extra_urls:e.target.value})}/></div><button className={s.primary} disabled={busy==='client'}>{busy==='client'?'Creating…':'Create client'}</button><div className={s.list}>{clients.map(c=><button type="button" className={s.item} key={c.id} onClick={()=>selectClient(c)}><span><b>{c.name}</b><small>{c.main_url}</small></span><span className={`${s.badge} ${c.status!=='approved'?s.warn:''}`}>{c.status}</span></button>)}</div></form>
 <div className={s.card}><h2>Sources & profile</h2>{activeClient?<><h3>{activeClient.name}</h3><div className={s.field}><label>PDF, POWERPOINT, TEXT OR MARKDOWN</label><input type="file" multiple onChange={e=>setFiles(e.target.files)}/></div><div className={s.actions}><button className={s.secondary} disabled={!files?.length||busy==='upload'} onClick={uploadSources}>Upload sources</button><button className={s.primary} disabled={!selectedClient||busy==='profile'} onClick={generateProfile}>Generate AI profile</button></div><div className={s.field}><label>SELLER INTELLIGENCE PROFILE · EDIT ONCE</label><textarea className={s.json} value={profileText} onChange={e=>setProfileText(e.target.value)}/></div><button className={s.primary} disabled={!profileText||busy==='approve'} onClick={approveProfile}>Approve seller profile</button></>:<p>Create or select a client first.</p>}</div></div>}
 {tab==='campaigns'&&<div className={s.grid}><form className={s.card} onSubmit={createCampaign}><h2>Create a campaign</h2><div className={s.field}><label>APPROVED CLIENT</label><select required value={campaignForm.client_id} onChange={e=>setCampaignForm({...campaignForm,client_id:e.target.value})}><option value="">Select…</option>{clients.filter(c=>c.status==='approved').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className={s.field}><label>CAMPAIGN NAME</label><input required value={campaignForm.name} onChange={e=>setCampaignForm({...campaignForm,name:e.target.value})}/></div><div className={s.field}><label>TARGET AUDIENCE</label><textarea required rows={4} value={campaignForm.target_audience} onChange={e=>setCampaignForm({...campaignForm,target_audience:e.target.value})}/></div><div className={s.field}><label>PERSONAS</label><input value={campaignForm.personas} onChange={e=>setCampaignForm({...campaignForm,personas:e.target.value})}/></div><button className={s.primary}>Create campaign</button></form><div className={s.card}><h2>Active campaigns</h2><div className={s.list}>{campaigns.map(c=><div className={s.item} key={c.id}><span><b>{c.name}</b><small>{c.target_audience}</small></span><span className={s.badge}>{c.active?'active':'paused'}</span></div>)}</div></div></div>}
 {tab==='prospects'&&<div className={s.grid}><form className={s.card} onSubmit={createProspect}><h2>Add a prospect</h2><div className={s.field}><label>CAMPAIGN</label><select required value={prospectForm.campaign_id} onChange={e=>setProspectForm({...prospectForm,campaign_id:e.target.value})}><option value="">Select…</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className={s.field}><label>COMPANY URL</label><input required type="url" value={prospectForm.company_url} onChange={e=>setProspectForm({...prospectForm,company_url:e.target.value})}/></div><div className={s.row}><div className={s.field}><label>COMPANY NAME</label><input value={prospectForm.company_name} onChange={e=>setProspectForm({...prospectForm,company_name:e.target.value})}/></div><div className={s.field}><label>CONTACT NAME</label><input value={prospectForm.contact_name} onChange={e=>setProspectForm({...prospectForm,contact_name:e.target.value})}/></div></div><div className={s.row}><div className={s.field}><label>TITLE</label><input value={prospectForm.contact_title} onChange={e=>setProspectForm({...prospectForm,contact_title:e.target.value})}/></div><div className={s.field}><label>EMAIL</label><input type="email" value={prospectForm.contact_email} onChange={e=>setProspectForm({...prospectForm,contact_email:e.target.value})}/></div></div><div className={s.field}><label>LINKEDIN URL</label><input value={prospectForm.linkedin_url} onChange={e=>setProspectForm({...prospectForm,linkedin_url:e.target.value})}/></div><div className={s.field}><label>EXTRA URLS / NOTES</label><textarea rows={3} value={prospectForm.extra_urls} onChange={e=>setProspectForm({...prospectForm,extra_urls:e.target.value})}/><textarea rows={3} value={prospectForm.notes} onChange={e=>setProspectForm({...prospectForm,notes:e.target.value})}/></div><button className={s.primary}>Add prospect</button></form><div className={s.card}><h2>Prospects</h2><div className={s.list}>{prospects.map(p=><div className={s.item} key={p.id}><span><b>{p.company_name||p.company_url}</b><small>{p.status} · stage {p.stage}/5 · {Math.round(p.confidence*100)}%</small></span><div className={s.actions}>{p.status==='new'&&<button className={s.secondary} onClick={()=>researchProspect(p.id)}>Research</button>}<button className={s.secondary} onClick={()=>viewEvidence(p.id)}>Evidence</button><button className={s.primary} onClick={()=>generateEmail(p.id)}>Next email</button></div></div>)}</div></div></div>}
 {tab==='evidence'&&<div className={s.grid}><div className={s.card}><h2>Strategic brief</h2>{activeProspect?<><h3>{activeProspect.company_name||activeProspect.company_url}</h3><p><b>Next:</b> {activeProspect.next_action}</p><pre className={s.email}>{JSON.stringify(activeProspect.strategic_brief,null,2)}</pre><h3>Narrative blueprint</h3><div className={s.list}>{activeProspect.blueprint?.map((b:any)=><div className={s.item} key={b.stage}><span><b>{b.stage}. {b.chapter}</b><small>{b.purpose}</small></span></div>)}</div></>:<p>Select Evidence from a prospect.</p>}</div><div className={s.card}><h2>Evidence Ledger</h2><div className={s.ledger}>{evidence.map(e=><div className={s.evidence} key={e.id}><b>{e.fact}</b><small>{e.kind.replaceAll('_',' ')} · {Math.round(e.confidence*100)}% · {e.evidence_type}<br/>{e.source}</small></div>)}</div>{email&&<><h2>Next email only</h2><div className={s.field}><label>SUBJECT</label><input value={email.subject} onChange={e=>setEmail({...email,subject:e.target.value})}/></div><div className={s.email}>{email.body}</div><div className={s.field}><label>AUTO-SELECTED CTA · EDITABLE</label><input value={email.cta} onChange={e=>setEmail({...email,cta:e.target.value})}/></div><div className={s.actions}><button className={s.secondary} onClick={()=>navigator.clipboard.writeText(email.subject)}>Copy subject</button><button className={s.primary} onClick={()=>navigator.clipboard.writeText(email.body)}>Copy body</button></div></>}</div></div>}
 {tab==='batch'&&<div className={s.grid}><div className={s.card}><h2>Import prospects</h2><p>Required column: <b>company_url</b>. Standard contact fields and custom columns are preserved.</p><div className={s.field}><label>CAMPAIGN</label><select value={prospectForm.campaign_id} onChange={e=>setProspectForm({...prospectForm,campaign_id:e.target.value})}><option value="">Select…</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className={s.field}><label>CSV FILE</label><input type="file" accept=".csv" onChange={e=>setCsv(e.target.files?.[0]||null)}/></div><button className={s.primary} disabled={!csv||!prospectForm.campaign_id} onClick={importCsv}>Import CSV</button></div><div className={s.card}><h2>Export next actions</h2><p>Exports only each prospect’s next actionable email. Replied, suppressed, closed, and not-yet-due records are excluded.</p><div className={s.field}><label>CAMPAIGN</label><select value={prospectForm.campaign_id} onChange={e=>setProspectForm({...prospectForm,campaign_id:e.target.value})}><option value="">Select…</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><button className={s.primary} disabled={!prospectForm.campaign_id} onClick={()=>window.open(`${API}/api/batch/export/${prospectForm.campaign_id}?generate=true`,'_blank')}>Generate and download next-email CSV</button></div></div>}
 </div>
}
